plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.services)
}

android {
    namespace 'com.example.graduationproject'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.graduationproject"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.androidx.credentials
    implementation libs.androidx.credentials.play.services.auth

    // مكتبات الواجهة والتصميم من ملف TOML
    implementation libs.appcompat
    implementation libs.googleid
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.cardview
    implementation libs.preference

    // مكتبات الخرائط والبيانات
    implementation libs.google.maps
    implementation libs.google.play.services.base
    implementation libs.google.play.services.location
    implementation libs.osmdroid
    implementation libs.gson

        implementation 'org.osmdroid:osmdroid-android:6.1.20'



        implementation 'org.maplibre.gl:android-sdk:10.2.0' // تحقق من أحدث إصدار


    // إضافة مكتبة Glide
    implementation libs.glide
    annotationProcessor libs.glide.compiler

    // 1. استيراد منصة Firebase BoM (إصدار مستقر)
    implementation platform(libs.firebase.bom)

    // 2. مكتبات الفايربيس (تأخذ إصداراتها تلقائياً وبأمان من الـ BoM أعلاه)
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-messaging'

    // Test dependencies
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
